# ===== CONFIGURAÇÃO DO NETLIFY =====
# Definições para build e deploy

[build]
  command = "netlify deploy --prod"  # Comando de build
  functions = "netlify/functions"    # Diretório de funções serverless
  publish = "./"                     # Diretório raiz para publicação

  ## Configurações desativadas (comentadas)
  ## Redirecionamentos para SPA (Não necessário neste projeto)
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## Configurações para desenvolvimento local (desativadas)
  #[dev]
  #  command = "yarn start" # Comando para servidor de desenvolvimento
  #  port = 3000 # Porta para o servidor de desenvolvimento
  #  publish = "dist" # Pasta com conteúdo estático para arquivo _redirect